apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: arshadg2117/pgha:1.6
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: server-ip-service
spec:
  type: NodePort
  selector:
    component: server
  ports:
    - port: 3000
