apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres3-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: postgres3
  template:
    metadata:
      labels:
        component: postgres3
    spec:
      containers:
        - name: postgres3
          image: postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres3-storage
              mountPath: /var/lib/postgresql/data
          env:
            - name: "POSTGRES_PASSWORD"
              value: "admin123"
            - name: "POSTGRES_DB"
              value: "postgres"
      volumes:
        - name: postgres3-storage
          persistentVolumeClaim:
            claimName: postgres-claim-3

---
apiVersion: v1
kind: Service
metadata:
  name: postgres3-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: postgres3
  ports:
    - port: 5432
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-claim-3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-storage-pv-3
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/kubepostgres/data3"
    type: DirectoryOrCreate
